Fixed some compilation and build errors in QueryEvaluator, QueryProjector and IntergrationTest. Remaining bugs: Error C2338 The C++ Standard doesn't provide a hash for this type. SPA G:\Softs\Visual Studio 2015\VC\include\xstddef 377